
<?php
/**
 * @file
 * Code for the feature feature.
 */

include_once 'blog_feature.features.inc';

/**
 * Implements hook_init().
 */
function blog_feature_init() {
  drupal_add_js(drupal_get_path('module', 'blog_feature') .'/blog_feature.js');
}

/**
 * Implements hook_integration().
 */
function blog_feature_integration() {
  // Add links to views if a module wants to do that.
  return array(
    'blog_feature' => array(
      'entity' => array(
        'node'=> array(
          'blog' => array(
            'add_content_link' => TRUE,
            'image'=> array(
              'enabled' => TRUE,
            ),
          ),
        ),
      ),
      'views' => array(
        'blog' => array(
          'block' => array(
            'add_content_link' => array(
              'areas' => array('footer'),
            ),
          ),
        ),
      ),
    ),
  );
}
